/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f96780bb90d1fec7b7101b3a26bccb02)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Fetcher /* spritex-ai */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
